### ISSUE TITLE
能不能加个游戏运行后关闭"TenioDL.exe"的功能啊

### ISSUE THREAD

**Issue by yeezylife** [H3d9/sguard_limit#10]
我现在玩LOL得在登陆账号之后手动关这个进程。（另外这个进程关闭游戏也会继续运行）

以前可以直接用windows自带的‘软件限制策略’拦住，最近重装之后直接拦住"TenioDL.exe"的话，游戏会弹出"您当前的客户端版本不支持校验"，不让登陆。。。

**Comment by H3d9** [comment]
您可以去Colg论坛搜索“神秘力量”即可

**Comment by yeezylife** [comment]
谢谢指路，有的时候工具有，看了说明也会用。。。但是连工具存在都不知道。
