### ISSUE TITLE
对外请求

### ISSUE THREAD

**Issue by GGZDDR** [H3d9/sguard_limit#17]
![image](https://github.com/H3d9/sguard_limit/assets/51272548/24ecba84-5fb1-471a-853a-1867e74151ba)
为啥这个软件一直在请求gitee？我在源码搜索gitee关键字并不存在

**Comment by H3d9** [comment]
需要联网检查更新。
gitee关键字出现在win32utility.cpp: win32SystemManager::_grabCloudData()函数中。
