### ISSUE TITLE
StartService 失败，0x800b010c 证书已被颁发者直接吊销

### ISSUE THREAD

**Issue by Lovely-Ruby** [H3d9/sguard_limit#18]
![Snipaste_2024-02-08_07-29-37](https://github.com/H3d9/sguard_limit/assets/24784282/a24b9b55-6dd6-4112-be5f-2baa4fe465a3)
作者您好，修复错误弹窗的版本报错了

**Comment by H3d9** [comment]
用7.12版，B专栏有
