### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Wangcheng1923** [H3d9/sguard_limit#5]
老哥换了win11之后就这样了 
下面是日志

hijack thread: pid found.
patch(): entering.
patch().driver.load(): StartService失败。重启电脑应该能解决该问题。
note: error (0x1f) 连到系统上的设备没有发挥作用。

**Comment by H3d9** [comment]
win11最新版去群里下载另一个sys就可以了
默认只支持到22519，高版本如果改了偏移还用就会蓝屏（目前还没改），所以我故意分开了。

**Comment by Wangcheng1923** [comment]
> 

好的谢谢了
