### ISSUE TITLE
运行时异常

### ISSUE THREAD

**Issue by evalexp** [H3d9/sguard_limit#9]
运行时会异常，已更新至最新版本（22.9.21）.
![image](https://user-images.githubusercontent.com/72970177/191694291-369faaf9-9da5-4c6c-8a99-c875895242e3.png)

**Comment by H3d9** [comment]
先重启下电脑然后重新下载即可

**Comment by evalexp** [comment]
> 

已经发现问题所在。
不能先启动游戏，先启动游戏则会出现上述异常，必须先启动这个程序再启动游戏即可。
